name: MoneroOne
options:
  bundleIdPrefix: one.monero
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

packages:
  MoneroKit:
    url: https://github.com/horizontalsystems/MoneroKit.Swift.git
    exactVersion: 0.1.13
  HdWalletKit:
    url: https://github.com/horizontalsystems/HdWalletKit.Swift.git
    exactVersion: 1.3.0

targets:
  MoneroOne:
    type: application
    platform: iOS
    sources:
      - MoneroOne
      - Shared
    dependencies:
      - package: MoneroKit
      - package: HdWalletKit
      - target: MoneroOneWidgets
        embed: true
    info:
      path: MoneroOne/Info.plist
      properties:
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleDisplayName: "Monero One"
        UIBackgroundModes:
          - location
        NSSupportsLiveActivities: true
        NSLocationAlwaysAndWhenInUseUsageDescription: "Background sync uses location services to keep your wallet synced. Location data is never stored or transmitted."
        NSLocationWhenInUseUsageDescription: "Enable background sync to keep your wallet updated."
        NSCameraUsageDescription: "Camera is used to scan QR codes"
        NSFaceIDUsageDescription: "Face ID is used to unlock your wallet"
    settings:
      base:
        INFOPLIST_FILE: MoneroOne/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: true
        ASSETCATALOG_COMPILER_APPICON_NAME: monero-one
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

  MoneroOneWidgets:
    type: app-extension
    platform: iOS
    sources:
      - MoneroOneWidgets
      - Shared
    info:
      path: MoneroOneWidgets/Info.plist
      properties:
        CFBundleDisplayName: "Monero Sync"
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
        NSSupportsLiveActivities: true
    settings:
      base:
        GENERATE_INFOPLIST_FILE: false
        INFOPLIST_FILE: MoneroOneWidgets/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: one.monero.MoneroOne.Widgets
        SWIFT_EMIT_LOC_STRINGS: true
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks @executable_path/../../Frameworks"

  MoneroOneTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - MoneroOneTests
    dependencies:
      - target: MoneroOne
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true

  MoneroOneUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - MoneroOneUITests
    dependencies:
      - target: MoneroOne
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        TEST_TARGET_NAME: MoneroOne

schemes:
  MoneroOne:
    build:
      targets:
        MoneroOne: all
        MoneroOneTests: [test]
        MoneroOneUITests: [test]
    test:
      targets:
        - MoneroOneTests
        - MoneroOneUITests
